(function(){'use strict';var videojs=null;if(typeof window.videojs==='undefined'&&typeof require==='function'){videojs=require('video.js');}else{videojs=window.videojs;}
(function(window,videojs){var defaults={},videoJsResolutionSwitcher,currentResolution={},menuItemsHolder={};function setSourcesSanitized(player,sources,label,customSourcePicker){currentResolution={label:label,sources:sources};if(typeof customSourcePicker==='function'){return customSourcePicker(player,sources,label);}
return player.src(sources.map(function(src){return{src:src.src,type:src.type,res:src.res};}));}
var MenuItem=videojs.getComponent('MenuItem');var ResolutionMenuItem=videojs.extend(MenuItem,{constructor:function(player,options,onClickListener,label){this.onClickListener=onClickListener;this.label=label;MenuItem.call(this,player,options);this.src=options.src;this.on('click',this.onClick);this.on('touchstart',this.onClick);if(options.initialySelected){this.showAsLabel();this.selected(true);this.addClass('vjs-selected');}},showAsLabel:function(){if(this.label){this.label.innerHTML=this.options_.label;}},onClick:function(customSourcePicker){this.onClickListener(this);var currentTime=this.player_.currentTime();var isPaused=this.player_.paused();this.showAsLabel();this.addClass('vjs-selected');if(!isPaused){this.player_.bigPlayButton.hide();}
if(typeof customSourcePicker!=='function'&&typeof this.options_.customSourcePicker==='function'){customSourcePicker=this.options_.customSourcePicker;}
var handleSeekEvent='loadeddata';if(this.player_.techName_!=='Youtube'&&this.player_.preload()==='none'&&this.player_.techName_!=='Flash'){handleSeekEvent='timeupdate';}
setSourcesSanitized(this.player_,this.src,this.options_.label,customSourcePicker).one(handleSeekEvent,function(){this.player_.currentTime(currentTime);this.player_.handleTechSeeked_();if(!isPaused){this.player_.play().handleTechSeeked_();}
this.player_.trigger('resolutionchange');});}});var MenuButton=videojs.getComponent('MenuButton');var ResolutionMenuButton=videojs.extend(MenuButton,{constructor:function(player,options,settings,label){this.sources=options.sources;this.label=label;this.label.innerHTML=options.initialySelectedLabel;MenuButton.call(this,player,options,settings);this.controlText('Quality');if(settings.dynamicLabel){this.el().appendChild(label);}else{var staticLabel=document.createElement('span');videojs.addClass(staticLabel,'vjs-resolution-button-staticlabel');this.el().appendChild(staticLabel);}},createItems:function(){var menuItems=[];var labels=(this.sources&&this.sources.label)||{};var onClickUnselectOthers=function(clickedItem){menuItems.map(function(item){item.selected(item===clickedItem);item.removeClass('vjs-selected');});};for(var key in labels){if(labels.hasOwnProperty(key)){menuItems.push(new ResolutionMenuItem(this.player_,{label:key,src:labels[key],initialySelected:key===this.options_.initialySelectedLabel,customSourcePicker:this.options_.customSourcePicker},onClickUnselectOthers,this.label));menuItemsHolder[key]=menuItems[menuItems.length-1];}}
return menuItems;}});videoJsResolutionSwitcher=function(options){var settings=videojs.mergeOptions(defaults,options),player=this,label=document.createElement('span'),groupedSrc={};videojs.addClass(label,'vjs-resolution-button-label');player.updateSrc=function(src){if(!src){return player.src();}
if(player.controlBar.resolutionSwitcher){player.controlBar.resolutionSwitcher.dispose();delete player.controlBar.resolutionSwitcher;}
src=src.sort(compareResolutions);groupedSrc=bucketSources(src);var choosen=chooseSrc(groupedSrc,src);var menuButton=new ResolutionMenuButton(player,{sources:groupedSrc,initialySelectedLabel:choosen.label,initialySelectedRes:choosen.res,customSourcePicker:settings.customSourcePicker},settings,label);videojs.addClass(menuButton.el(),'vjs-resolution-button');player.controlBar.resolutionSwitcher=player.controlBar.el_.insertBefore(menuButton.el_,player.controlBar.getChild('fullscreenToggle').el_);player.controlBar.resolutionSwitcher.dispose=function(){this.parentNode.removeChild(this);};return setSourcesSanitized(player,choosen.sources,choosen.label);};player.currentResolution=function(label,customSourcePicker){if(label==null){return currentResolution;}
if(menuItemsHolder[label]!=null){menuItemsHolder[label].onClick(customSourcePicker);}
return player;};player.getGroupedSrc=function(){return groupedSrc;};function compareResolutions(a,b){if(!a.res||!b.res){return 0;}
return(+b.res)-(+a.res);}
function bucketSources(src){var resolutions={label:{},res:{},type:{}};src.map(function(source){initResolutionKey(resolutions,'label',source);initResolutionKey(resolutions,'res',source);initResolutionKey(resolutions,'type',source);appendSourceToKey(resolutions,'label',source);appendSourceToKey(resolutions,'res',source);appendSourceToKey(resolutions,'type',source);});return resolutions;}
function initResolutionKey(resolutions,key,source){if(resolutions[key][source[key]]==null){resolutions[key][source[key]]=[];}}
function appendSourceToKey(resolutions,key,source){resolutions[key][source[key]].push(source);}
function chooseSrc(groupedSrc,src){var selectedRes=settings['default'];var selectedLabel='';if(selectedRes==='high'){selectedRes=src[0].res;selectedLabel=src[0].label;}else if(selectedRes==='low'||selectedRes==null||!groupedSrc.res[selectedRes]){selectedRes=src[src.length-1].res;selectedLabel=src[src.length-1].label;}else if(groupedSrc.res[selectedRes]){selectedLabel=groupedSrc.res[selectedRes][0].label;}
return{res:selectedRes,label:selectedLabel,sources:groupedSrc.res[selectedRes]};}
function initResolutionForYt(player){player.tech_.ytPlayer.setPlaybackQuality('default');player.tech_.ytPlayer.addEventListener('onPlaybackQualityChange',function(){player.trigger('resolutionchange');});player.one('play',function(){var qualities=player.tech_.ytPlayer.getAvailableQualityLevels();var _yts={highres:{res:1080,label:'1080',yt:'highres'},hd1080:{res:1080,label:'1080',yt:'hd1080'},hd720:{res:720,label:'720',yt:'hd720'},large:{res:480,label:'480',yt:'large'},medium:{res:360,label:'360',yt:'medium'},small:{res:240,label:'240',yt:'small'},tiny:{res:144,label:'144',yt:'tiny'},auto:{res:0,label:'auto',yt:'default'}};var _sources=[];qualities.map(function(q){_sources.push({src:player.src().src,type:player.src().type,label:_yts[q].label,res:_yts[q].res,_yt:_yts[q].yt});});groupedSrc=bucketSources(_sources);var _customSourcePicker=function(_player,_sources,_label){player.tech_.ytPlayer.setPlaybackQuality(_sources[0]._yt);return player;};var choosen={label:'auto',res:0,sources:groupedSrc.label.auto};var menuButton=new ResolutionMenuButton(player,{sources:groupedSrc,initialySelectedLabel:choosen.label,initialySelectedRes:choosen.res,customSourcePicker:_customSourcePicker},settings,label);menuButton.el().classList.add('vjs-resolution-button');player.controlBar.resolutionSwitcher=player.controlBar.addChild(menuButton);});}
player.ready(function(){if(player.options_.sources.length>1){player.updateSrc(player.options_.sources);}
if(player.techName_==='Youtube'){initResolutionForYt(player);}});};videojs.plugin('videoJsResolutionSwitcher',videoJsResolutionSwitcher);})(window,videojs);})();
console.log('zoomrotate: Start');(function(){var defaults,extend;console.log('zoomrotate: Init defaults');defaults={zoom:1,rotate:0,debug:true};extend=function(){var args,target,i,object,property;args=Array.prototype.slice.call(arguments);target=args.shift()||{};for(i in args){object=args[i];for(property in object){if(object.hasOwnProperty(property)){if(typeof object[property]==='object'){target[property]=extend(target[property],object[property]);}else{target[property]=object[property];}}}}
return target;};videojs.plugin('zoomrotate',function(settings){if(defaults.debug)console.log('zoomrotate: Register init');var options,player,video,poster;options=extend(defaults,settings);player=this.el();video=this.el().getElementsByTagName('video')[0];poster=this.el().getElementsByTagName('div')[1];if(options.debug)console.log('zoomrotate: '+video.style);if(options.debug)console.log('zoomrotate: '+poster.style);if(options.debug)console.log('zoomrotate: '+options.rotate);if(options.debug)console.log('zoomrotate: '+options.zoom);var properties=['transform','WebkitTransform','MozTransform','msTransform','OTransform'],prop=properties[0];var i,j;for(i=0,j=properties.length;i<j;i++){if(typeof player.style[properties[i]]!=='undefined'){prop=properties[i];break;}}
player.style.overflow='hidden';video.style[prop]='scale('+options.zoom+') rotate('+options.rotate+'deg)';poster.style[prop]='scale('+options.zoom+') rotate('+options.rotate+'deg)';if(options.debug)console.log('zoomrotate: Register end');});})();console.log('zoomrotate: End');